In [6]:
#Question 1.
#Import dataset and save x and y 

from sklearn.datasets import load_digits
digits = load_digits()
x = digits.data
y = digits.target


In [7]:
#Question 2.
#fit the data using k means
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 10)
kmeans.fit(x)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=10, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [29]:
#predict the data using kmeans
predict = kmeans.predict(x)
print(predict)

[3 1 1 ... 1 4 4]


In [30]:
print(kmeans.labels_)

[3 1 1 ... 1 4 4]


In [31]:
#Question 3.
#Use of zero_like() and mode() functions.

import numpy as np
from scipy.stats import mode
from sklearn.metrics import accuracy_score,confusion_matrix
labels = np.zeros_like(predict)
for i in range(3):
    mask = (predict==i)
    labels[mask] = mode(y[mask])[0]


In [33]:
#Question 4.

print("accuracy_score",accuracy_score(y,labels))
print("\nconfusion_matrix\n",confusion_matrix(y, labels))

accuracy_score 0.31886477462437396

confusion_matrix
 [[178   0   0   0   0   0   0   0   0   0]
 [ 81   0   0   1   0   1   0   0  99   0]
 [156   0   0  13   0   0   0   0   8   0]
 [ 17   0   0 157   0   2   0   0   7   0]
 [178   0   0   0   0   0   0   0   3   0]
 [ 45   0   0   1   0 136   0   0   0   0]
 [179   0   0   0   0   0   0   0   2   0]
 [177   0   0   0   0   0   0   0   2   0]
 [ 65   0   0   3   0   4   0   0 102   0]
 [166   0   0   6   0   6   0   0   2   0]]


In [48]:
#IMAGE
#Question 1.
from sklearn.datasets import load_sample_image
import matplotlib.pyplot as plt
flower = load_sample_image('flower.jpg')
plt.imshow(flower)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\datasets\base.py:762: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  images = [imread(filename) for filename in filenames]
C:\Users\user\Anaconda3\lib\site-packages\sklearn\datasets\base.py:762: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  images = [imread(filename) for filename in filenames]


In [47]:
#Question 2.

print(flower.shape)

(427, 640, 3)


In [51]:
#Question 3.
#reshape the dimensions
x, y, z = flower.shape
image_2d = flower.reshape(x*y, z)
print(image_2d.shape)

(273280, 3)


In [54]:
#Question 4.
#fit the clusters into 7 clusters
kmeans = KMeans(n_clusters = 7)
kmeans.fit(image_2d)


KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=7, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)