In [1]:
#Question 1.
import numpy as np

np_arr = np.random.randint(100, size=(10,1))
print(np_arr)
print("mean=",np.mean(np_arr))


[[14]
 [39]
 [30]
 [95]
 [35]
 [92]
 [32]
 [95]
 [ 6]
 [65]]
mean= 50.3


In [2]:
#Question 2.
np_arr = np.random.randint(100, size=(20,1))
print(np_arr)

print("variance=",np.var(np_arr))
print("standard deviation=",np.std(np_arr))


[[69]
 [57]
 [10]
 [62]
 [15]
 [38]
 [96]
 [43]
 [68]
 [24]
 [67]
 [77]
 [30]
 [28]
 [95]
 [93]
 [73]
 [75]
 [18]
 [39]]
variance= 723.3275
standard deviation= 26.89474855803638


In [4]:
#Question 3.
a = np.random.randint(10, size=(10,20))
b = np.random.randint(10, size=(20,25))
c = np.matmul(a,b)
print("MATRIX A:\n",a)
print("MATRIX B:\n",b)
print("MATRIX C:\n",c)
print("\n\nShape of matrix C:",np.shape(c))
print("Sum of elements of Matrix C:",np.sum(c))


MATRIX A:
 [[2 8 2 6 6 8 8 1 8 6 6 1 5 5 1 8 6 8 5 8]
 [0 8 4 4 2 0 6 8 6 4 5 6 6 2 5 7 0 3 3 2]
 [3 5 0 9 1 0 5 9 1 4 1 0 7 2 7 9 6 2 6 0]
 [0 4 1 9 4 4 8 2 6 2 1 1 4 3 2 9 4 8 4 4]
 [0 7 7 5 7 5 0 9 4 3 7 8 6 7 3 2 9 6 9 3]
 [8 4 9 8 8 2 6 9 3 1 1 3 1 1 8 3 6 2 2 8]
 [7 1 6 7 9 1 8 6 8 2 5 7 8 6 2 5 0 9 8 9]
 [8 0 4 9 4 9 7 3 1 7 5 2 9 9 3 5 4 1 2 0]
 [5 6 4 4 4 6 4 8 5 3 5 9 5 9 4 5 7 7 8 5]
 [8 8 1 1 4 9 6 2 1 2 8 7 3 1 0 4 7 7 6 4]]
MATRIX B:
 [[3 5 8 4 9 9 8 3 6 0 2 7 5 6 4 7 3 0 3 6 4 9 6 0 2]
 [0 2 7 2 5 2 6 7 6 3 3 7 4 8 0 9 2 3 4 4 4 4 4 1 2]
 [9 6 9 6 8 4 3 4 7 6 4 7 1 9 1 6 6 7 7 9 2 1 7 7 4]
 [3 0 5 9 1 0 3 8 8 7 1 4 5 8 4 9 2 2 8 5 9 8 5 4 0]
 [4 1 2 6 8 4 0 9 9 2 6 4 3 8 8 2 0 7 4 5 7 0 0 5 4]
 [0 2 1 5 0 0 1 8 3 2 7 8 1 3 3 7 0 2 0 1 6 5 1 1 6]
 [6 0 2 9 1 1 4 3 9 2 2 0 1 0 1 6 9 6 1 0 8 6 2 2 7]
 [3 2 5 5 3 7 9 8 2 6 1 4 5 7 1 6 5 8 5 3 4 5 4 7 1]
 [9 5 5 0 1 8 5 8 2 7 3 8 8 2 5 4 0 3 1 8 5 3 1 6 8]
 [8 4 5 7 0 0 9 9 0 9 4 8 8 3 4 6 0 4 4 9 6 7 3 2 4]
 [7 1 7 8 0 4 7 9

In [6]:
#Question 4.
import math
a = np.random.randint(10, size=(10,1))

def f(x):
    return(1/(1+math.exp(-x)))

arr = np.array(list(map(f,a)))
print(arr)
print(math.exp(10))

[0.99330715 0.99908895 0.5        0.88079708 0.99966465 0.99908895
 0.99908895 0.99330715 0.99966465 0.99966465]
22026.465794806718
